### ISSUE TITLE
Generating game list stuck at 0

### ISSUE THREAD

**Issue by sassanix** [SushyDev/vapor-store#11]
I have tried with https:// and without and it's still not moving for me.

**Comment by Nomad227** [comment]
Use an older version. Only 1 website works well with this program, and older verions (1.4.#) should be enough. The advanced webscraper does not always work well in my experience.

But, if you are adamant on using the newest version, do you have it configured correctly? Can you post what you have there? (black out website if you want)

**Comment by sassanix** [comment]
I tried the older version and the new one and both have this issue. A proper web source has been used as well.
![vapor](https://user-images.githubusercontent.com/39465071/83881417-fdf48100-a716-11ea-8a86-0491a3ea4364.jpg)

**Comment by EricPlayZ** [comment]
> 
> 
> I tried the older version and the new one and both have this issue. A proper web source has been used as well.
> ![vapor](https://user-images.githubusercontent.com/39465071/83881417-fdf48100-a716-11ea-8a86-0491a3ea4364.jpg)

You need to configure the generator properly like the game list query and the regex according to your web source.

**Comment by ThonkPT** [comment]
> 
> 
> > I tried the older version and the new one and both have this issue. A proper web source has been used as well.
> > ![vapor](https://user-images.githubusercontent.com/39465071/83881417-fdf48100-a716-11ea-8a86-0491a3ea4364.jpg)
> 
> You need to configure the generator properly like the game list query and the regex according to your web source.

problem is theres no documentiation on the only repository that works with this or if there is i wasnt able to find it after like 2 hours of google and reddit searching

**Comment by EricPlayZ** [comment]
> 
> 
> > > I tried the older version and the new one and both have this issue. A proper web source has been used as well.
> > > ![vapor](https://user-images.githubusercontent.com/39465071/83881417-fdf48100-a716-11ea-8a86-0491a3ea4364.jpg)
> > 
> > 
> > You need to configure the generator properly like the game list query and the regex according to your web source.
> 
> problem is theres no documentiation on the only repository that works with this or if there is i wasnt able to find it after like 2 hours of google and reddit searching

There is on their Discord server in the #faq channel.

**Comment by ThonkPT** [comment]
there is? damn
