### ISSUE TITLE
For some reason when I click on the buttons that lead to links in the Vapor Store Home, they don't redirect me and instead give errors in the console.

### ISSUE THREAD

**Issue by Rekulous** [SushyDev/vapor-store#27]
Issue in title and the buttons still haven't redirected me yet or opened my web browser. Check Discord for more issues and the video attached.

**Comment by SushyDev** [comment]
[Fixed](https://github.com/SushyDev/vapor-store/commit/718439c2654d565b547e68880de355beb06393da)

**Comment by Rekulous** [comment]
> [Fixed](https://github.com/SushyDev/vapor-store/commit/718439c2654d565b547e68880de355beb06393da)

Thanks sushy!
