### ISSUE TITLE
Some games have wrong metadata

### ISSUE THREAD

**Issue by Jeddunk** [SushyDev/vapor-store#3]
For example, the game ["Ashen"](https://www.igdb.com/games/ashen--1) is getting the metadata of [an old mobile phone game of the same name](https://www.igdb.com/games/ashen):
![image](https://user-images.githubusercontent.com/2891973/83025200-32897e00-a02f-11ea-840e-b9b5ad73a269.png)

A potential fix is to make sure that the metadata for the game includes the platform "PC (Microsoft Windows)"
e.g.: `where platforms = [6]` ([See docs for more info](https://api-docs.igdb.com/#platform))

**Comment by CrypticShy** [comment]
I have discovered that filtering by pc only will result into too many games losing their metadata due to only being able to search IGDB by game name but I'll filter it by excluding mobile but keeping console & pc as a solution for now
